# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.5
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pdm-project/pdm
  rev: 2.10.0 # a PDM release exposing the hook
  hooks:
    - id: pdm-lock-check
    - id: pdm-export
      # command arguments, e.g.:
      args: ['--prod', '-o', 'requirements.txt', '--without-hashes']
      files: ^pdm.lock$
    - id: pdm-export
      # command arguments, e.g.:
      args: ['--dev', '-o', 'requirements.dev.txt', '--without-hashes']
      files: ^pdm.lock$
