# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/taitac',
                'doc_host': 'https://nd-crane.github.io',
                'git_url': 'https://github.com/nd-crane/taitac',
                'lib_path': 'taitac'},
  'syms': {'taitac.core': {'taitac.core.foo': ('core.html#foo', 'taitac/core.py')}}}